[package]
name = "llama_ort"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "=2.0.0-rc.7"
ndarray = "0.16.1"
tokenizers = { version = "0.14.1", features = ["http"] }
rand = "0.8"
rand_distr = "0.4"